# Vagrant VMs
# https://docs.ansible.com/projects/ansible/latest/inventory_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters

[dashboard]
dashboard01 ansible_host=192.168.56.11

[counting]
counting01 ansible_host=192.168.56.12

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=/home/sai-wai-yan/pov-ansible/pov-ansible/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

# App variables used in the templates
dashboard_port=9002
counting_port=9003
counting_ip=192.168.56.12